name: pubs_financial
description: "Pubs Financial mobile app"
publish_to: "none"

version: 1.0.0+4

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
   
  url_launcher: ^6.3.0

  image_picker: ^1.1.2

  file_picker: ^8.0.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3

  # Networking
  dio: ^5.4.0

  # State management / routing
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0

  # Secure storage
  flutter_secure_storage: ^9.2.2

  # Biometrics
  local_auth: ^2.3.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  ios: true
  android: true
  image_path: assets/icon/app_icon.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
